Dockerfile: use go version 1.5.4-r0
This error recently appeared when building the Dockerfile:

ERROR: unsatisfiable constraints:
  go-1.5.4-r0:
    breaks: world[go=1.5.3-r0]

It looks that now upstream requires go 1.5.4-r0 not 1.5.3-r0.

License: MIT
Signed-off-by: Christian Couder <chriscool@tuxfamily.org>